apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 32.6.2
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
  name: localpv-provisioner
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: localpv-provisioner
  project: kubeaid
  sources:
    - repoURL: https://github.com/Obmondo/KubeAid.git
      path: argocd-helm-charts/localpv-provisioner
      targetRevision: 32.6.2
      helm:
        valueFiles:
          - $values/k8s/llm-test4/argocd-apps/values-localpv-provisioner.yaml
    - repoURL: https://github.com/Ahmad-Faizan/kubeaid-config.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
