git:
  sshUsername: git
  useSSHAgent: true

forkURLs:
  kubeaid:
    url: https://github.com/Obmondo/KubeAid.git
    version: 32.5.0
  kubeaidConfig:
    url: git@github.com:Ahmad-Faizan/kubeaid-config.git
    directory: 

cluster:
  type: workload
  name: llm-test1
  k8sVersion: v1.34.0
  enableAuditLogging: false
  apiServer:
    extraArgs: {}
    extraVolumes: []
    files: []
  argoCD:
    deployKeys:
      kubeaidConfig:
        privateKeyFilePath: /home/faizan/.ssh/id_rsa

kubePrometheus:
  version: v0.18.0

cloud:
  bare-metal:
    ssh:
      port: 22
    controlPlane:
      endpoint:
        host: 192.168.122.145
        port: 6443
      hosts:
        - publicAddress: 192.168.122.145


