global:
  clusterName: enableit.test.bw7.io
  customerid: faizan
  kubernetes:
    version: v1.29.0
  clusterAPI:
    version: v1.8.1
  capa:
    version: v2.6.1
    autoScaler: true
  kubeaid:
    repo: https://github.com/Archisman-Mridha/kubeaid.git
  kubeaidConfig:
    repo: https://github.com/Ahmad-Faizan/kubeaid-config.git

provider:
  aws: true

aws:
  secretName: capi-cluster-token
  sshKeyName: kubeaid-demo
  region: eu-west-1
  bastion:
    enabled: true
  vpc:
    cidrBlock: 10.12.0.0/16
  pods:
    cidrBlock: 192.168.0.0/16
  controlPlane:
    loadBalancerType: nlb
    region: eu-west-1
    replicas: 3
    instanceType: t4g.medium
    ami:
      id: ami-03cd26c84ae9a587c
  workerNodes:
    region: eu-west-1
    replicas: 2
    instanceType: t4g.medium
    ami:
      id: ami-03cd26c84ae9a587c
